### ISSUE TITLE
invalid write error in libjiagu.so

### ISSUE THREAD

**Issue by Ezreal147** [AeonLucid/AndroidNativeEmu#24]
I try to run libjiagu.so as mentioned in the beginning of the [article](https://bbs.pediy.com/thread-253868.htm) which may be written by @P4nda0s ,but I get UC_ERR_WRITE_UNMAPPED when the init_array of libjiagu.so is called. I have loaded all the .so needed, but it still crash
`2020-01-04 15:47:35,770   DEBUG        androidemu.internal.modules | Loading module './libjiagu.so'.
2020-01-04 15:47:35,772   DEBUG         androidemu.internal.memory | => Mapping memory page 0xcbd4f000 - 0xcbd5e000, size 0x0000f000, prot 5
2020-01-04 15:47:35,773   DEBUG         androidemu.internal.memory | => Mapping memory page 0xcbd5e000 - 0xcbdc8000, size 0x0006a000, prot 3
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/just crack me/AndroidNativeEmu-master/samples/example_jiagu.py", line 70, in <module>
    lib_module = emulator.load_library("./libjiagu.so",do_init=True)
  File "C:\Users\hp\Desktop\just crack me\AndroidNativeEmu-master\androidemu\emulator.py", line 124, in load_library
    self.call_native(fun_ptr)
  File "C:\Users\hp\Desktop\just crack me\AndroidNativeEmu-master\androidemu\emulator.py", line 152, in call_native
    self.mu.emu_start(addr, stop_pos - 1)
  File "D:\Python37\lib\site-packages\unicorn\unicorn.py", line 288, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
2020-01-04 15:47:35,792   DEBUG                androidemu.emulator | Calling Init for: ./libjiagu.so 
2020-01-04 15:47:35,793   DEBUG                androidemu.emulator | Calling Init function: cbd50ce0 `

**Comment by AeonLucid** [comment]
Possibly fixed now.

**Comment by Ezreal147** [comment]
now I get UC_ERR_INSN_INVALID in the init_array of libjiagu.so, and If I set libc++.so  `do_init=True`, programe will always run in its init_array and cant not jump out, like this 
`2020-01-06 13:24:38,375   DEBUG        androidemu.internal.modules | Loading module 'example_binaries/libc++.so'.`
`2020-01-06 13:24:38,376   DEBUG         androidemu.internal.memory | => Mapping memory page 0xcbc96000 - 0xcbd20000, size 0x0008a000, prot 5`
`2020-01-06 13:24:38,377   DEBUG         androidemu.internal.memory | => Mapping memory page 0xcbd21000 - 0xcbd27000, size 0x00006000, prot 3`
`2020-01-06 13:24:38,557   DEBUG                androidemu.emulator | Calling init for: example_binaries/libc++.so `
`2020-01-06 13:24:38,557   DEBUG                androidemu.emulator | Calling Init function: cbcc6741 `

**Comment by AeonLucid** [comment]
Please share your code including libjiagu.so.
