### ISSUE TITLE
Updated the libcms.so, and reported a error

### ISSUE THREAD

**Issue by dantin-s** [AeonLucid/AndroidNativeEmu#31]
I updated the libcms.so and meet argument worng type error:

```log
2020-02-15 13:27:33,793    INFO                           __main__ | Loaded modules:
2020-02-15 13:27:33,793    INFO                           __main__ | => 0xcbbcb000 - samples/example_binaries/libdl.so
2020-02-15 13:27:33,793    INFO                           __main__ | => 0xcbbd1000 - samples/example_binaries/libc.so
2020-02-15 13:27:33,793    INFO                           __main__ | => 0xcbc6c000 - samples/example_binaries/libstdc++.so
2020-02-15 13:27:33,794    INFO                           __main__ | => 0xcbc72000 - samples/example_binaries/libm.so
2020-02-15 13:27:33,794    INFO                           __main__ | => 0xcbc95000 - libcms.so
2020-02-15 13:27:33,799   DEBUG            androidemu.java.java_vm | java_vm: 0x01000056
2020-02-15 13:27:33,799   DEBUG            androidemu.java.java_vm | env: 0x000ff1d0
2020-02-15 13:27:33,799   DEBUG            androidemu.java.java_vm | version: 0x00010006
2020-02-15 13:27:33,799   DEBUG            androidemu.java.java_vm | JavaVM->GetENV() was called!
2020-02-15 13:27:33,803   DEBUG            androidemu.java.jni_env | JNIEnv->FindClass(com/ss/sys/ces/a) was called
2020-02-15 13:27:33,803   DEBUG            androidemu.java.jni_env | JNIEnv->ExceptionCheck() was called
2020-02-15 13:27:33,804   DEBUG            androidemu.java.jni_env | JNIEnv->NewGlobalRef(1) was called
2020-02-15 13:27:33,805   DEBUG            androidemu.java.jni_env | JNIEnv->RegisterNatives(1, 0x000ff118, 4) was called
2020-02-15 13:27:33,805 WARNING     androidemu.java.java_class_def | Register native ('meta', '(ILandroid/content/Context;Ljava/lang/Object;)Ljava/lang/Object;') failed on class XGorgen.
2020-02-15 13:27:33,805 WARNING     androidemu.java.java_class_def | Register native ('leviathan', '(II[B)[B') failed on class XGorgen.
2020-02-15 13:27:33,806 WARNING     androidemu.java.java_class_def | Register native ('decode', '(I[B)[B') failed on class XGorgen.
2020-02-15 13:27:33,806 WARNING     androidemu.java.java_class_def | Register native ('encode', '([B)[B') failed on class XGorgen.
Traceback (most recent call last):
  File "samples/example_douyin.py", line 157, in <module>
    result = x.leviathan(emulator, 1562848170, data)
  File "/Users/vincent/Github/AndroidNativeEmu/androidemu/java/java_method_def.py", line 24, in native_wrapper
    *argv  # Extra args.
  File "/Users/vincent/Github/AndroidNativeEmu/androidemu/emulator.py", line 147, in call_native
    self.mu.emu_start(addr, stop_pos - 1)
  File "/usr/local/lib/python3.7/site-packages/unicorn/unicorn.py", line 286, in emu_start
    status = _uc.uc_emu_start(self._uch, begin, until, timeout, count)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

```

The `leviathan` function is change, and has 3 parameter,
```java
public static native byte[] leviathan(int paramInt1, int paramInt2, byte[] paramArrayOfbyte);
```
How can i fix it ?

[libcms.so.zip](https://github.com/AeonLucid/AndroidNativeEmu/files/4207813/libcms.so.zip)

**Comment by harrisonwhiskey** [comment]
any reason why you wan to update the libcms.so?

**Comment by shiqwang** [comment]
It is a new version of libcms.so
