### ISSUE TITLE
cannot import name 'Ks' from 'keystone' on windows 10 python 3.7

### ISSUE THREAD

**Issue by liangzha856987** [AeonLucid/AndroidNativeEmu#34]
D:\AndroidNativeEmu-master\samples>python example.py
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    from androidemu.emulator import Emulator
  File "D:\AndroidNativeEmu-master\samples\androidemu\emulator.py", line 15, in <module>
    from androidemu.hooker import Hooker
  File "D:\AndroidNativeEmu-master\samples\androidemu\hooker.py", line 1, in <module>
    from keystone import Ks, KS_ARCH_ARM, KS_MODE_THUMB
ImportError: cannot import name 'Ks' from 'keystone' (D:\Python37\lib\site-packages\keystone\__init__.py)

I'm new to keystone,  got this message when fisrt run example, 
did lots of google but no idea how to fix it.

**Comment by Heartfilia** [comment]
maybe you could try "pip install keystone-engine --upgrade" to fix it
