### ISSUE TITLE
运行example.py报错了

### ISSUE THREAD

**Issue by guanlingji** [AeonLucid/AndroidNativeEmu#38]
requirements.txt已成功执行

但是在运行example.py却出现以下错误

D:\py_workspace\AndroidNativeEmu-master\samples> python .\example.py
Traceback (most recent call last):
  File ".\example.py", line 7, in <module>
    from androidemu.emulator import Emulator
ModuleNotFoundError: No module named 'androidemu'

**Comment by KevinWang22** [comment]
把androidemu整个文件夹复制到samples里面

**Comment by guanlingji** [comment]
已经解决了,谢谢

**Comment by axhlzy** [comment]
root@kali:~/Desktop/workspace/AndroidNativeEmu-master/androidemu/samples# python3 example_jiagu.py 
Traceback (most recent call last):
  File "example_jiagu.py", line 8, in <module>
    from androidemu.emulator import Emulator
  File "/root/.local/share/Trash/files/samples/androidemu/emulator.py", line 24, in <module>
    from androidemu.vfs.file_system import VirtualFileSystem
  File "/root/.local/share/Trash/files/samples/androidemu/vfs/file_system.py", line 11, in <module>
    from samples import debug_utils
ModuleNotFoundError: No module named 'samples'


这个是cp了整个文件夹的  还是报错了诶
