### ISSUE TITLE
JNI can't found the Java classes , how to fix it ?

### ISSUE THREAD

**Issue by deathmemory** [AeonLucid/AndroidNativeEmu#4]
when i call `JNI_Onload`
```python
# load xxx.so and call the JNI_OnLoad
emulator.call_symbol(libdidiwsg, 'JNI_OnLoad', emulator.java_vm.address_ptr, 0x00)
``` 

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/unicorn/unicorn.py", line 438, in _hookcode_cb
    cb(self, address, size, data)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/androidemu/hooker.py", line 97, in _hook
    hook_func(self._emu)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/androidemu/java/helpers/native_method.py", line 104, in native_method_wrapper
    result = func(argv[0], mu, *native_args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/androidemu/java/jni_env.py", line 350, in find_class
    raise RuntimeError('Could not find class \'%s\' for JNIEnv.' % name)
RuntimeError: Could not find class 'android/content/Context' for JNIEnv.
```
JNI can't found the Java classes , how to fix it ?
If I load Context class manually, it have has another class not found 
Do I have to load all the classes manually?

**Comment by AeonLucid** [comment]
Yes you are supposed to create all classes it needs.
See https://github.com/AeonLucid/AndroidNativeEmu/blob/master/androidemu/java/classes/method.py ([more](https://github.com/AeonLucid/AndroidNativeEmu/tree/master/androidemu/java/classes)) for an exampl.

**Comment by deathmemory** [comment]
OK,thankyou
