### ISSUE TITLE
About libcms.so

### ISSUE THREAD

**Issue by LukeJean** [AeonLucid/AndroidNativeEmu#48]
Hello, libcms.so updated, but after I replaced the new file, the program reported an error.
```
Traceback (most recent call last):
  File "example_douyin.py", line 128, in <module>
    lib_module = emulator.load_library("./example_binaries/libcms.so")
  File "..\androidemu\emulator.py", line 117, in load_library
    self.call_native(fun_ptr)
  File "..\androidemu\emulator.py", line 143, in call_native
    self.mu.emu_start(addr, stop_pos - 1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\unicorn\unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
```

**Comment by ii64** [comment]
Try to put libc.so into vfs/system/lib

**Comment by angelag2347** [comment]
f5e409a08c03caa20eed605ef31e1e7827d803cd
