### ISSUE TITLE
NotImplementedError: Symbol hook not implemented pthread_create

### ISSUE THREAD

**Issue by lidongbo** [AeonLucid/AndroidNativeEmu#53]
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/python37/lib/python3.7/site-packages/unicorn/unicorn.py", line 480, in _hookcode_cb
    cb(self, address, size, data)
  File "/data/SO-Mock/samples/androidemu/hooker.py", line 97, in _hook
    hook_func(self._emu)
  File "/data/SO-Mock/samples/androidemu/java/helpers/native_method.py", line 110, in native_method_wrapper
    result = func(mu, *native_args)
  File "/data/SO-Mock/samples/androidemu/native/hooks.py", line 143, in nop_inside
    raise NotImplementedError('Symbol hook not implemented %s' % name)
NotImplementedError: Symbol hook not implemented pthread_create
Traceback (most recent call last):
  File "example_mt.py", line 144, in <module>
    logger.info("Response from JNI call: %s" % main_activity.getCandyDataWithKey(emulator, data, ""))
  File "/data/SO-Mock/samples/androidemu/java/java_method_def.py", line 24, in native_wrapper
    *argv  # Extra args.
  File "/data/SO-Mock/samples/androidemu/emulator.py", line 143, in call_native
    self.mu.emu_start(addr, stop_pos - 1)
  File "/usr/local/python37/lib/python3.7/site-packages/unicorn/unicorn.py", line 316, in emu_start
    status = _uc.uc_emu_start(self._uch, begin, until, timeout, count)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by angelag2347** [comment]
f5e409a08c03caa20eed605ef31e1e7827d803cd
