### ISSUE TITLE
I'm having trouble running example_douyin.py

### ISSUE THREAD

**Issue by bwmaples** [AeonLucid/AndroidNativeEmu#9]
I run the example_douyin.py and I meet this problem when running example_douyin.py

I think the problem is in java_method_def.py Line 20, native_wrapper.jvm_method.native_addr. The value of this address is assigned to None. But I don't know how to fix it.

2019-09-04 11:30:53,910   DEBUG    androidemu.cpu.syscall_handlers | Executing syscall madvise(02181000, 00003000, 0000000c) at 0xcbc1b78c
2019-09-04 11:30:53,910   DEBUG    androidemu.cpu.syscall_handlers | Executing syscall munmap(02181000, 00003000) at 0xcbc1b8f4
2019-09-04 11:30:53,920   DEBUG                samples.debug_utils | mem unmapped: pc: cbd0a8a8 access: 13 address: fffff734 length: 4 value: 0
@Tsingxing None
Traceback (most recent call last):
  File ".\example_douyin.py", line 152, in <module>
    result = x.leviathan(emulator, 1562848170, data)
  File "F:\code\AndroidNativeEmu-master_another\AndroidNativeEmu-master\androidemu\java\java_method_def.py", line 25, in native_wrapper
    *argv  # Extra args.
  File "F:\code\AndroidNativeEmu-master_another\AndroidNativeEmu-master\androidemu\emulator.py", line 147, in call_native
    self.mu.emu_start(addr, stop_pos - 1)
  File "C:\Users\tingxinluan\AppData\Local\Programs\Python\Python37\lib\site-packages\unicorn\unicorn.py", line 286, in emu_start
    status = _uc.uc_emu_start(self._uch, begin, until, timeout, count)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by AeonLucid** [comment]
Related https://github.com/AeonLucid/AndroidNativeEmu/issues/8

**Comment by bwmaples** [comment]
Okay, I got it
